# Generated by Django 2.1.5 on 2019-01-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinner_name', models.CharField(max_length=240)),
                ('dinner_ingredients', models.CharField(max_length=240)),
                ('dinner_instructions', models.CharField(max_length=240)),
            ],
        ),
    ]
